/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;
import MyCustom.SelectCustomerOrDiscount;
import DAO.KhachHangDAO;
import DTO.KhachHangDTO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class InforCustomer extends javax.swing.JFrame{
    private SelectCustomerOrDiscount listener;
    private SelectCustomerOrDiscount listener1;
    
    public void setSelectCustomerListener(SelectCustomerOrDiscount listener) {
        this.listener = listener;
    }
    
    public void setSelectCustomer1Listener(SelectCustomerOrDiscount listener){
        this.listener1 = listener;
    }

    @Override
    public void setTransferHandler(TransferHandler newHandler)
    {
        super.setTransferHandler(newHandler); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public TransferHandler getTransferHandler()
    {
        return super.getTransferHandler(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    /** Creates new form InforCustomer */
    public InforCustomer() {
        initComponents();
        loadDataFromSource();
    }
    
   private void loadDataFromSource() {
        // --- Nạp dữ liệu cho Bảng Hóa Đơn ---
        DefaultTableModel modelHoaDon = (DefaultTableModel) TCustomer.getModel();
        modelHoaDon.setRowCount(0); // Xóa dữ liệu cũ trước khi nạp mới
        try {
             KhachHangDAO a = new KhachHangDAO();
             ArrayList<KhachHangDTO> dsKH = a.layDSKH();
            if (dsKH != null) {
                for (KhachHangDTO kh : dsKH) {
                    Object[] rowData = {
                        kh.getMaKH(),
                        kh.getHoLot()+" "+kh.getTenKH(),
                        kh.getSDT(),
                        kh.getDiaChi()
                    };
                    modelHoaDon.addRow(rowData);
                }
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách khách hàng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SPane = new javax.swing.JScrollPane();
        TCustomer = new javax.swing.JTable();
        BtnChooseCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng Khách Hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        SPane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SPane.setPreferredSize(new java.awt.Dimension(580, 460));
        SPane.getViewport().setBackground(Color.WHITE);

        TCustomer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Mã khách hàng", "Họ và tên", "Số điện thoại", "Địa chỉ"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return false;
            }
        });
        SPane.setViewportView(TCustomer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(SPane, gridBagConstraints);

        BtnChooseCustomer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnChooseCustomer.setText("Chọn Khách Hàng");
        BtnChooseCustomer.setMaximumSize(new java.awt.Dimension(170, 30));
        BtnChooseCustomer.setMinimumSize(new java.awt.Dimension(170, 30));
        BtnChooseCustomer.setPreferredSize(new java.awt.Dimension(170, 30));
        BtnChooseCustomer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnChooseCustomerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 20;
        jPanel1.add(BtnChooseCustomer, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnChooseCustomerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnChooseCustomerActionPerformed
    {//GEN-HEADEREND:event_BtnChooseCustomerActionPerformed
        // TODO add your handling code here:
        int row = TCustomer.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng trong bảng khách hàng" , "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            String ma_kh = TCustomer.getModel().getValueAt(row,0).toString();
            String ten_kh = TCustomer.getModel().getValueAt(row, 1).toString();
            JOptionPane.showMessageDialog(this, String.format("Bạn đã chọn khách hàng %s", ten_kh) , "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            if(listener != null){
                listener.onCustomerSelected(Integer.parseInt(ma_kh),ten_kh);
            }
            if(listener1 != null){
                listener1.onCustomer1Selected(Integer.parseInt(ma_kh), ten_kh);
            }
            this.dispose();
        }
    }//GEN-LAST:event_BtnChooseCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnChooseCustomer;
    private javax.swing.JScrollPane SPane;
    private javax.swing.JTable TCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
