/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author ADMIN
 */
public class InforAccount extends javax.swing.JFrame
{
   public static String formatDate(String inputDate) {
       LocalDate date = LocalDate.parse(inputDate, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
    }
    
    public InforAccount(String username, String password, int idNV, String tenNV, String ngaysinh, String gioitinh, String quyen){
        initComponents();
        TFUsername.setText(username);
        TFPassword.setText(password);
        FTFIdStaff.setValue(idNV);
        TFStaffName.setText(tenNV);
        FTNS.setText(formatDate(ngaysinh));
        TFGT.setText(gioitinh);
        TFPermission.setText(quyen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        LblTitle = new javax.swing.JLabel();
        LblUsername = new javax.swing.JLabel();
        TFUsername = new javax.swing.JTextField();
        LblIdStaff = new javax.swing.JLabel();
        LblStaffName = new javax.swing.JLabel();
        TFStaffName = new javax.swing.JTextField();
        LblPermission = new javax.swing.JLabel();
        TFPermission = new javax.swing.JTextField();
        FTFIdStaff = new javax.swing.JFormattedTextField();
        LblPassword = new javax.swing.JLabel();
        TFPassword = new javax.swing.JTextField();
        LblNS = new javax.swing.JLabel();
        FTNS = new javax.swing.JFormattedTextField();
        LblGT = new javax.swing.JLabel();
        TFGT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông Tin Tài Khoản");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LblTitle.setBackground(new java.awt.Color(255, 255, 255));
        LblTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("Thông Tin Tài Khoản");
        LblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LblTitle, gridBagConstraints);

        LblUsername.setBackground(new java.awt.Color(255, 255, 255));
        LblUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblUsername.setText("Tên Đăng Nhập");
        LblUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblUsername, gridBagConstraints);

        TFUsername.setEditable(false);
        TFUsername.setBackground(new java.awt.Color(255, 255, 255));
        TFUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TFUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(TFUsername, gridBagConstraints);

        LblIdStaff.setBackground(new java.awt.Color(255, 255, 255));
        LblIdStaff.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblIdStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIdStaff.setText("Mã Nhân Viên");
        LblIdStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblIdStaff, gridBagConstraints);

        LblStaffName.setBackground(new java.awt.Color(255, 255, 255));
        LblStaffName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblStaffName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblStaffName.setText("Tên Nhân Viên");
        LblStaffName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblStaffName, gridBagConstraints);

        TFStaffName.setEditable(false);
        TFStaffName.setBackground(new java.awt.Color(255, 255, 255));
        TFStaffName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TFStaffName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(TFStaffName, gridBagConstraints);

        LblPermission.setBackground(new java.awt.Color(255, 255, 255));
        LblPermission.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblPermission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPermission.setText("Quyền");
        LblPermission.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblPermission, gridBagConstraints);

        TFPermission.setEditable(false);
        TFPermission.setBackground(new java.awt.Color(255, 255, 255));
        TFPermission.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TFPermission.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(TFPermission, gridBagConstraints);

        FTFIdStaff.setEditable(false);
        FTFIdStaff.setBackground(new java.awt.Color(255, 255, 255));
        FTFIdStaff.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTFIdStaff.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(FTFIdStaff, gridBagConstraints);

        LblPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPassword.setText("Mật Khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblPassword, gridBagConstraints);

        TFPassword.setEditable(false);
        TFPassword.setBackground(new java.awt.Color(255, 255, 255));
        TFPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TFPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(TFPassword, gridBagConstraints);

        LblNS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblNS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNS.setText("Ngày sinh");
        LblNS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblNS, gridBagConstraints);

        FTNS.setEditable(false);
        FTNS.setBackground(new java.awt.Color(255, 255, 255));
        FTNS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTNS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(FTNS, gridBagConstraints);

        LblGT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblGT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblGT.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(LblGT, gridBagConstraints);

        TFGT.setEditable(false);
        TFGT.setBackground(new java.awt.Color(255, 255, 255));
        TFGT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TFGT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        getContentPane().add(TFGT, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FTFIdStaff;
    private javax.swing.JFormattedTextField FTNS;
    private javax.swing.JLabel LblGT;
    private javax.swing.JLabel LblIdStaff;
    private javax.swing.JLabel LblNS;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblPermission;
    private javax.swing.JLabel LblStaffName;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JTextField TFGT;
    private javax.swing.JTextField TFPassword;
    private javax.swing.JTextField TFPermission;
    private javax.swing.JTextField TFStaffName;
    private javax.swing.JTextField TFUsername;
    // End of variables declaration//GEN-END:variables
}
