/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import BUS.QuyenBUS;

import DTO.NhanVienDTO;
import DTO.QuyenDTO;
import MyCustom.MyDialog;
import MyCustom.TableCustomizer;

import com.formdev.flatlaf.json.ParseException;
import org.apache.poi.ss.usermodel.Cell;

import java.awt.GridLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JCheckBox;
import javax.swing.JFileChooser;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.JTextField;

import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author somna
 */
public class PnNhanVien3 extends javax.swing.JPanel {

    private final NhanVienBUS nvBUS;

    /**
     * Creates new form PnNhanVien1
     */
    public PnNhanVien3() {
        initComponents();
        nvBUS = new NhanVienBUS(); // Khởi tạo NhanVienBUS
        txtMaNV.setText(String.valueOf(nvBUS.getMAX()));
        loadDataToTable(); // Tải dữ liệu nhân viên lên JTable
        loadDataCmbQuyen();
        loadChiTietQuyen();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        PnTitle1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblMaNV5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblMaNV1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoLot = new javax.swing.JTextField();
        lblMaNV2 = new javax.swing.JLabel();
        lblMaNV3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblHoDem6 = new javax.swing.JLabel();
        lblHoDem5 = new javax.swing.JLabel();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnNhapEx = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCapTaiKhoan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbbNhomQuyen = new javax.swing.JComboBox<>();
        lblTitle2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbBanHang = new javax.swing.JLabel();
        lbKhuyenMai = new javax.swing.JLabel();
        lbSanPham = new javax.swing.JLabel();
        lbNhanVien = new javax.swing.JLabel();
        lbKhachHang = new javax.swing.JLabel();
        lbNhapHang = new javax.swing.JLabel();
        lbThongKe = new javax.swing.JLabel();
        cbBanHang = new javax.swing.JCheckBox();
        cbKhuyenMai = new javax.swing.JCheckBox();
        cbSanPham = new javax.swing.JCheckBox();
        cbNhanVien = new javax.swing.JCheckBox();
        cbKhachHang = new javax.swing.JCheckBox();
        cbNhapHang = new javax.swing.JCheckBox();
        cbThongKe = new javax.swing.JCheckBox();
        btnThemQuyen = new javax.swing.JButton();
        btnXoaQuyen = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 247, 247));

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        PnTitle1.setBackground(new java.awt.Color(247, 247, 247));

        lblTitle1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle1.setText("Quản lý nhân viên");

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Refresh-icon.png"))); // NOI18N
        btnReset.setName(""); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnTitle1Layout = new javax.swing.GroupLayout(PnTitle1);
        PnTitle1.setLayout(PnTitle1Layout);
        PnTitle1Layout.setHorizontalGroup(
            PnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTitle1Layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnReset)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        PnTitle1Layout.setVerticalGroup(
            PnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTitle1Layout.createSequentialGroup()
                .addGroup(PnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnTitle1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnTitle1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblMaNV5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblMaNV5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search-icon.png"))); // NOI18N
        lblMaNV5.setText("Tìm kiếm");

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pencil-icon.png"))); // NOI18N
        btnSua.setText("Lưu");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));

        lblMaNV1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblMaNV1.setText("Mã nhân viên");

        txtMaNV.setEditable(false);
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        txtHoLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoLotActionPerformed(evt);
            }
        });

        lblMaNV2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblMaNV2.setText("Họ đệm");

        lblMaNV3.setBackground(new java.awt.Color(247, 247, 247));
        lblMaNV3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblMaNV3.setText("Tên");

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        lblHoDem6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblHoDem6.setText("Ngày sinh");

        lblHoDem5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblHoDem5.setText("Giới tính");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn giới tính :", "Nam", "Nữ" }));
        cbbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioiTinhActionPerformed(evt);
            }
        });

        txtNgaySinh.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHoDem6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblHoDem5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblMaNV3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaNV1)
                                    .addComponent(lblMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoLot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoLot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV2))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblHoDem6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoDem5)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        btnNhapEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel-icon.png"))); // NOI18N
        btnNhapEx.setText("Nhập");
        btnNhapEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapExActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel-icon.png"))); // NOI18N
        jButton5.setText("Xuất");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnCapTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_man_with_key_32px.png"))); // NOI18N
        btnCapTaiKhoan.setText("Cấp tài khoản");
        btnCapTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMaNV5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNhapEx)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCapTaiKhoan))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PnTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaNV5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNhapEx)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapTaiKhoan)
                        .addContainerGap(158, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel1);

        cbbNhomQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhomQuyenActionPerformed(evt);
            }
        });

        lblTitle2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle2.setText("Quản lý phân quyền");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nhóm quyền");

        lbBanHang.setText("Quản lý bán hàng");

        lbKhuyenMai.setText("Quản lý khuyến mãi ");

        lbSanPham.setText("Quản lý sản phầm");

        lbNhanVien.setText("Quản lý nhân viên");

        lbKhachHang.setText("Quản lý khách hàng ");

        lbNhapHang.setText("Quản lý nhập hàng");

        lbThongKe.setText("Thống kê");

        cbBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBanHangActionPerformed(evt);
            }
        });

        cbKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhuyenMaiActionPerformed(evt);
            }
        });

        cbSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSanPhamActionPerformed(evt);
            }
        });

        cbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhanVienActionPerformed(evt);
            }
        });

        cbKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhachHangActionPerformed(evt);
            }
        });

        cbNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhapHangActionPerformed(evt);
            }
        });

        cbThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThongKeActionPerformed(evt);
            }
        });

        btnThemQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-icon.png"))); // NOI18N
        btnThemQuyen.setText("Thêm quyền");
        btnThemQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemQuyenActionPerformed(evt);
            }
        });

        btnXoaQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-icon.png"))); // NOI18N
        btnXoaQuyen.setText("Xóa quyền");
        btnXoaQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaQuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(cbbNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBanHang)
                            .addComponent(lbKhuyenMai)
                            .addComponent(lbSanPham)
                            .addComponent(lbNhanVien)
                            .addComponent(lbKhachHang)
                            .addComponent(lbNhapHang)
                            .addComponent(lbThongKe))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbThongKe)
                            .addComponent(cbNhapHang)
                            .addComponent(cbKhachHang)
                            .addComponent(cbNhanVien)
                            .addComponent(cbSanPham)
                            .addComponent(cbKhuyenMai)
                            .addComponent(cbBanHang))))
                .addGap(535, 535, 535))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(btnThemQuyen)
                        .addGap(114, 114, 114)
                        .addComponent(btnXoaQuyen)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(53, 53, 53)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(cbbNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel1))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(lbBanHang)
                                                            .addComponent(cbBanHang))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lbKhuyenMai))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbKhuyenMai)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbSanPham))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(cbSanPham)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbNhanVien))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cbNhanVien)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbKhachHang))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbKhachHang)))
                        .addGap(15, 15, 15)
                        .addComponent(lbNhapHang))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbNhapHang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThongKe)
                    .addComponent(cbThongKe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemQuyen)
                    .addComponent(btnXoaQuyen))
                .addGap(220, 220, 220))
        );

        jTabbedPane1.addTab("Quyền", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGioiTinhActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtHoLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoLotActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
        txtMaNV.setText(String.valueOf(nvBUS.getMAX()));
        loadDataToTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        xuatExcel();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnNhapExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapExActionPerformed
        nhapExcel();
    }//GEN-LAST:event_btnNhapExActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        xulysuanhanvien();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        xuLyThemNhanVien();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        try {
            hienThiThongTinNhanVienTuTable();
        } catch (java.text.ParseException ex) {
            Logger.getLogger(PnNhanVien3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        xulynutxoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        timKiemNhanVien();
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void btnCapTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapTaiKhoanActionPerformed
        int row = tblNhanVien.getSelectedRow();
        if (row != -1) {
            String maNVString = tblNhanVien.getValueAt(row, 0).toString();
            try {
                int maNV = Integer.parseInt(maNVString);
                DlgCapTaiKhoan dlg = new DlgCapTaiKhoan(maNV); // Tạo dialog, đã tự động tải dữ liệu trong constructor
                dlg.setVisible(true); // Hiển thị dialog
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhân viên trước!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        loadDataToTable();
    }//GEN-LAST:event_btnCapTaiKhoanActionPerformed

    private void cbbNhomQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhomQuyenActionPerformed
        loadChiTietQuyen();
    }//GEN-LAST:event_cbbNhomQuyenActionPerformed

    private void cbBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBanHangActionPerformed
        capNhatQuyen(cbBanHang, "QLBanHang");
    }//GEN-LAST:event_cbBanHangActionPerformed

    private void cbKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhuyenMaiActionPerformed
        capNhatQuyen(cbKhuyenMai, "QLKhuyenMai");
    }//GEN-LAST:event_cbKhuyenMaiActionPerformed

    private void cbSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSanPhamActionPerformed
        capNhatQuyen(cbSanPham, "QLSanPham");
    }//GEN-LAST:event_cbSanPhamActionPerformed

    private void cbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhanVienActionPerformed
        capNhatQuyen(cbNhanVien, "QLNhanVien");
    }//GEN-LAST:event_cbNhanVienActionPerformed

    private void cbKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhachHangActionPerformed
        capNhatQuyen(cbKhachHang, "QLKhachHang");
    }//GEN-LAST:event_cbKhachHangActionPerformed

    private void cbNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhapHangActionPerformed
        capNhatQuyen(cbNhapHang, "QLNhapHang");
    }//GEN-LAST:event_cbNhapHangActionPerformed

    private void cbThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThongKeActionPerformed
        capNhatQuyen(cbThongKe, "ThongKe");
    }//GEN-LAST:event_cbThongKeActionPerformed

    private void btnThemQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemQuyenActionPerformed
        themQuyenMoi();
    }//GEN-LAST:event_btnThemQuyenActionPerformed

    private void btnXoaQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaQuyenActionPerformed
        // Lấy quyền đang chọn từ combobox
        QuyenDTO quyen = (QuyenDTO) cbbNhomQuyen.getSelectedItem();

        if (quyen != null) {
            // Lấy mã quyền từ đối tượng QuyenDTO
            int maQuyen = quyen.getMaQuyen(); // Giả sử bạn có phương thức getMaQuyen() trong QuyenDTO

            // Gọi phương thức xóa quyền từ QuyenBUS
            QuyenBUS quyenBUS = new QuyenBUS(); // Tạo đối tượng QuyenBUS nếu chưa có sẵn
            boolean isDeleted = quyenBUS.xoaQuyen(maQuyen);

            if (isDeleted) {
                // Nếu xóa thành công, xóa quyền khỏi combobox
                cbbNhomQuyen.removeItem(quyen);

                // Hiển thị thông báo cho người dùng
                JOptionPane.showMessageDialog(this, "Quyền đã được xóa.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn quyền cần xóa.");
        }
    }//GEN-LAST:event_btnXoaQuyenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnTitle1;
    private javax.swing.JButton btnCapTaiKhoan;
    private javax.swing.JButton btnNhapEx;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemQuyen;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaQuyen;
    private javax.swing.JCheckBox cbBanHang;
    private javax.swing.JCheckBox cbKhachHang;
    private javax.swing.JCheckBox cbKhuyenMai;
    private javax.swing.JCheckBox cbNhanVien;
    private javax.swing.JCheckBox cbNhapHang;
    private javax.swing.JCheckBox cbSanPham;
    private javax.swing.JCheckBox cbThongKe;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<QuyenDTO> cbbNhomQuyen;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbBanHang;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbKhuyenMai;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbNhapHang;
    private javax.swing.JLabel lbSanPham;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lblHoDem5;
    private javax.swing.JLabel lblHoDem6;
    private javax.swing.JLabel lblMaNV1;
    private javax.swing.JLabel lblMaNV2;
    private javax.swing.JLabel lblMaNV3;
    private javax.swing.JLabel lblMaNV5;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtHoLot;
    private javax.swing.JTextField txtMaNV;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
    private void loadDataToTable() {
        String[] columnNames = {"Mã NV", "Họ đệm", "Tên", "Ngày sinh", "Giới tính", "Tên đăng nhập", "Mật Khẩu", " Quyền"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        ArrayList<Object[]> dsThongTin = nvBUS.hienThiTaiKhoanNhanVien();

        for (Object[] row : dsThongTin) {
            model.addRow(row);
        }

        tblNhanVien.setModel(model);
        TableCustomizer.customize(tblNhanVien);
    }

    private void clearForm() {
        txtMaNV.setText("");
        txtHoLot.setText("");
        txtTen.setText("");
        txtNgaySinh.setDate(null); // Clear date picker
        cbbGioiTinh.setSelectedIndex(0); // Reset to "Chọn giới tính :"
    }

    private void xuLyThemNhanVien() {
        if (cbbGioiTinh.getSelectedIndex() == 0) {
            new MyDialog("Hãy chọn giới tính!", MyDialog.ERROR_DIALOG);
            return;
        }

        if (txtNgaySinh.getDate() == null) {
            new MyDialog("Hãy chọn ngày sinh!", MyDialog.ERROR_DIALOG);
            return;
        }

        String ho = txtHoLot.getText().trim();
        String ten = txtTen.getText().trim();
        String gioiTinh = cbbGioiTinh.getSelectedItem().toString();

        // Chuyển ngày sinh thành chuỗi (kiểu String)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngaySinh = sdf.format(txtNgaySinh.getDate());

        if (nvBUS.themNhanVien(ho, ten, gioiTinh, ngaySinh)) {
            nvBUS.getDanhSachNhanVien();
            loadDataToTable();
            clearForm();
        }
    }

    private void xulysuanhanvien() {
        if (cbbGioiTinh.getSelectedIndex() == 0) {
            new MyDialog("Hãy chọn giới tính!", MyDialog.ERROR_DIALOG);
            return;
        }

        if (txtNgaySinh.getDate() == null) {
            new MyDialog("Hãy chọn ngày sinh!", MyDialog.ERROR_DIALOG);
            return;
        }

        String maNVchu = txtMaNV.getText().trim(); // Lấy MaNV từ text field
        int maNV = Integer.parseInt(maNVchu);
        String ho = txtHoLot.getText().trim();
        String ten = txtTen.getText().trim();
        String gioiTinh = cbbGioiTinh.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngaySinh = sdf.format(txtNgaySinh.getDate());

        if (nvBUS.Suanhanvien(maNV, ho, ten, gioiTinh, ngaySinh)) {
            nvBUS.getDanhSachNhanVien();
            loadDataToTable();
            clearForm();
        }
    }

    private void xulynutxoa() {
        int row = tblNhanVien.getSelectedRow(); // Lấy dòng đang chọn

        if (row == -1) {
            new MyDialog("Vui lòng chọn nhân viên để xóa!", MyDialog.ERROR_DIALOG);
            return;
        }
        String maNVchu = txtMaNV.getText().trim();
        int maNV = Integer.parseInt(maNVchu);
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn xóa nhân viên này?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            nvBUS.xoaNhanVienMem(maNV);
            loadDataToTable();
        }
    }

    private void timKiemNhanVien() {
        String tuKhoa = txtSearch.getText().trim(); // Lấy giá trị từ ô tìm kiếm

        if (tuKhoa.isEmpty()) { // Kiểm tra nếu ô tìm kiếm trống
            loadDataToTable(); // Nếu trống, tải lại toàn bộ dữ liệu
            return; // Không cần tìm kiếm
        }

        // Gọi BUS để lấy danh sách nhân viên theo từ khóa
        ArrayList<NhanVienDTO> dsNV = nvBUS.timKiemNhanVien(tuKhoa);

        // Cập nhật bảng với danh sách kết quả tìm kiếm
        String[] columnNames = {"Mã NV", "Họ đệm", "Tên", "Ngày sinh", "Giới tính"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (NhanVienDTO nv : dsNV) {
            Object[] rowData = {
                nv.getMaNV(),
                nv.getHoLot(),
                nv.getTen(),
                nv.getNgaysinh(),
                nv.getGioiTinh()
            };
            model.addRow(rowData);
        }
        tblNhanVien.setModel(model);
        TableCustomizer.customize(tblNhanVien); // Tùy chỉnh giao diện bảng
    }

    private void hienThiThongTinNhanVienTuTable() throws java.text.ParseException {
        int row = tblNhanVien.getSelectedRow();
        if (row == -1) {
            return;
        }

        String maNV = tblNhanVien.getValueAt(row, 0).toString();
        String hoLot = tblNhanVien.getValueAt(row, 1).toString();
        String ten = tblNhanVien.getValueAt(row, 2).toString();

        txtMaNV.setText(maNV);
        txtHoLot.setText(hoLot);
        txtTen.setText(ten);

        // Set ngày sinh vào JDateChooser
        try {
            String ngaySinhStr = tblNhanVien.getValueAt(row, 3).toString(); // Lấy chuỗi ngày sinh từ cột 3
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(ngaySinhStr);
            txtNgaySinh.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(PnNhanVien3.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gioitinh = tblNhanVien.getValueAt(row, 4).toString();
        if (gioitinh.equals("Nam")) {
            cbbGioiTinh.setSelectedIndex(1);
        } else {
            cbbGioiTinh.setSelectedIndex(2);
        }
    }
//    QUYỀN

    private void loadDataCmbQuyen() {
        cbbNhomQuyen.removeAllItems();
        QuyenBUS.docDanhSachQuyen();
        ArrayList<QuyenDTO> dsq = QuyenBUS.getListQuyen();
        for (QuyenDTO q : dsq) {
            cbbNhomQuyen.addItem(q);  // Thêm QuyenDTO vào ComboBox
        }
    }

    private void themQuyenMoi() {
        JTextField txtTenQuyen = new JTextField();

        JPanel panel = new JPanel(new GridLayout(2, 1, 5, 5));
        panel.add(new JLabel("Nhập tên quyền mới:"));
        panel.add(txtTenQuyen);

        int result = JOptionPane.showConfirmDialog(this, panel, "Thêm quyền mới",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String tenQuyenMoi = txtTenQuyen.getText().trim();

            if (tenQuyenMoi.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên quyền không được để trống.");
                return;
            }

            QuyenBUS quyenBUS = new QuyenBUS();

            for (QuyenDTO q : QuyenBUS.getListQuyen()) {
                if (q.getTenQuyen().equalsIgnoreCase(tenQuyenMoi)) {
                    JOptionPane.showMessageDialog(this, "Quyền này đã tồn tại.");
                    return;
                }
            }

            QuyenDTO quyenMoi = new QuyenDTO();
            quyenMoi.setTenQuyen(tenQuyenMoi); // Chỉ cần set tên

            if (quyenBUS.themQuyen(quyenMoi)) {
                JOptionPane.showMessageDialog(this, "Đã thêm quyền: " + tenQuyenMoi);
                loadDataCmbQuyen();
                cbbNhomQuyen.setSelectedItem(tenQuyenMoi);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm quyền thất bại.");
            }
        }

    }

    private void loadChiTietQuyen() {
        QuyenDTO q = (QuyenDTO) cbbNhomQuyen.getSelectedItem();
        if (q != null) {
            cbBanHang.setSelected(q.getQLBanHang());
            cbKhuyenMai.setSelected(q.getQLKhuyenMai());
            cbSanPham.setSelected(q.getQLSanPham());
            cbNhanVien.setSelected(q.getQLNhanVien());
            cbKhachHang.setSelected(q.getQLKhachHang());
            cbNhapHang.setSelected(q.getQLNhapHang());
            cbThongKe.setSelected(q.getThongKe());
        } else {
            // Reset các checkbox nếu không có quyền nào được chọn
            cbBanHang.setSelected(false);
            cbKhuyenMai.setSelected(false);
            cbSanPham.setSelected(false);
            cbNhanVien.setSelected(false);
            cbKhachHang.setSelected(false);
            cbNhapHang.setSelected(false);
            cbThongKe.setSelected(false);
        }
    }

    private void capNhatQuyen(JCheckBox checkbox, String tenQuyen) {
        QuyenDTO q = (QuyenDTO) cbbNhomQuyen.getSelectedItem();
        if (q != null) {
            boolean giaTri = checkbox.isSelected();
            switch (tenQuyen) {
                case "QLBanHang" ->
                    q.setQLBanHang(giaTri);
                case "QLKhuyenMai" ->
                    q.setQLKhuyenMai(giaTri);
                case "QLSanPham" ->
                    q.setQLSanPham(giaTri);
                case "QLNhanVien" ->
                    q.setQLNhanVien(giaTri);
                case "QLKhachHang" ->
                    q.setQLKhachHang(giaTri);
                case "QLNhapHang" ->
                    q.setQLNhapHang(giaTri);
                case "ThongKe" ->
                    q.setThongKe(giaTri);
            }
            QuyenBUS qBUS = new QuyenBUS();
            qBUS.capnhatquyen(q);  // Cập nhật quyền vào cơ sở dữ liệu
        }
    }

    public void nhapExcel() {
        try {
            // Tạo đối tượng JFileChooser để chọn file Excel
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn file Excel");

            // Mở hộp thoại cho phép người dùng chọn file
            int result = fileChooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                // Lấy file được chọn
                File file = fileChooser.getSelectedFile();
                FileInputStream fis = new FileInputStream(file);
                XSSFWorkbook workbook = new XSSFWorkbook(fis);
                XSSFSheet sheet = workbook.getSheetAt(0);  // Lấy sheet đầu tiên

                // Định dạng ngày
                SimpleDateFormat excelDateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Format của Excel
                SimpleDateFormat mysqlDateFormat = new SimpleDateFormat("yyyy-MM-dd");  // Format của MySQL

                // Duyệt qua các dòng trong Excel (bỏ qua dòng đầu tiên nếu đó là header)
                for (Row row : sheet) {
                    // Bỏ qua dòng header (dòng 0)
                    if (row.getRowNum() == 0) {
                        continue;
                    }

                    // Lấy giá trị từ các cột
                    String hoLot = row.getCell(0).getStringCellValue();  // Cột Họ Lót
                    String ten = row.getCell(1).getStringCellValue();    // Cột Tên
                    String ngaySinhStr = row.getCell(2).getStringCellValue();  // Cột Ngày Sinh (Là Text)
                    String gioiTinh = row.getCell(3).getStringCellValue();  // Cột Giới Tính

                    // Chuyển đổi định dạng ngày
                    String ngaySinhFormatted;
                    try {
                        Date ngaySinhDate = excelDateFormat.parse(ngaySinhStr); // Parse chuỗi ngày từ Excel
                        ngaySinhFormatted = mysqlDateFormat.format(ngaySinhDate); // Format lại thành YYYY-MM-DD
                    } catch (Exception e) {
                        System.out.println("Lỗi định dạng ngày cho nhân viên " + hoLot + " " + ten + ": " + ngaySinhStr);
                        continue; // Bỏ qua dòng này nếu ngày không hợp lệ
                    }

                    // Gọi hàm thêm nhân viên với ngày đã được định dạng
                    nvBUS.themNhanVien(hoLot, ten, gioiTinh, ngaySinhFormatted);
                    loadDataToTable();
                }

                fis.close();  // Đóng file Excel
            }

        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void xuatExcel() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu tệp Excel");
        fileChooser.setSelectedFile(new File("DanhSachNhanVien.xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            try (XSSFWorkbook workbook = new XSSFWorkbook()) {
                XSSFSheet sheet = workbook.createSheet("Danh sách nhân viên");

                // Tạo tiêu đề cột
                DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
                Row headerRow = sheet.createRow(0);
                for (int i = 0; i < model.getColumnCount(); i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                }

                // Ghi dữ liệu từ bảng vào Excel
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object value = model.getValueAt(i, j);
                        row.createCell(j).setCellValue(value != null ? value.toString() : "");
                    }
                }

                // Ghi tệp Excel ra đĩa
                try (FileOutputStream fileOut = new FileOutputStream(fileToSave)) {
                    workbook.write(fileOut);
                }

                JOptionPane.showMessageDialog(this, "Xuất dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
