/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import MyCustom.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;


/**
 *
 * @author somna
 */
public class QLBanHang extends javax.swing.JPanel {
    
    /**
     * Creates new form PnNhanVien1
     */
    public QLBanHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        SaleManagement = new javax.swing.JTabbedPane();
        PanelReceipt = new javax.swing.JPanel();
        SubPanelSale = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableReceipt = new javax.swing.JTable();
        BtnSortReceipt = new javax.swing.JButton();
        LblListReceipts = new javax.swing.JLabel();
        BtnResetReceipt = new javax.swing.JButton();
        BtnInforReceipt = new javax.swing.JButton();
        IconTextField abc= new IconTextField(100);
        abc.setIcon(FontAwesomeSolid.USER, 16, Color.GRAY);
        abc.setToolTipText("Click vô đây để chọn điều kiện để lọc");
        TfEllipsisReceipt = abc;
        SubPanelDetailSale = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableDetailReceipt = new javax.swing.JTable();
        LblDetailReceipt = new javax.swing.JLabel();
        LblSubTotalReceipt = new javax.swing.JLabel();
        LblReceiptDiscount = new javax.swing.JLabel();
        LblReceiptDiscountId = new javax.swing.JLabel();
        LblDateReceipt = new javax.swing.JLabel();
        DPDateReceipt = new com.github.lgooddatepicker.components.DatePicker();
        TfSubTotalReceipt = new javax.swing.JTextField();
        TfReceiptDiscount = new javax.swing.JTextField();
        TfReceiptDiscountId = new javax.swing.JTextField();
        PanelSale = new javax.swing.JPanel();
        PanelTitleSale = new javax.swing.JPanel();
        LblTitleSale = new javax.swing.JLabel();
        BtnSaleReset = new javax.swing.JButton();
        PanelDetailProduct = new javax.swing.JPanel();
        LblProductID = new javax.swing.JLabel();
        TfProductID = new javax.swing.JTextField();
        TfProductName = new javax.swing.JTextField();
        LblProductName = new javax.swing.JLabel();
        LblPriceQuotation = new javax.swing.JLabel();
        TfPriceQuotation = new javax.swing.JTextField();
        LblQuantity = new javax.swing.JLabel();
        LblTypeProduct = new javax.swing.JLabel();
        LblEmployee = new javax.swing.JLabel();
        CbbTypeProduct = new javax.swing.JComboBox<>();
        LblDetailProducts = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDetailProduct = new javax.swing.JTable();
        BtnDeleteSale = new javax.swing.JButton();
        ProductImage = new ImagePanel("src/main/resources/SanPham/default.png",160, 160);
        BtnMakeReceipt = new javax.swing.JButton();
        BtnAddBasket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBaskets = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1228, 746));

        SaleManagement.setBackground(new java.awt.Color(255, 255, 255));
        SaleManagement.setPreferredSize(new java.awt.Dimension(1226, 730));

        PanelReceipt.setBackground(new java.awt.Color(255, 255, 255));
        PanelReceipt.setPreferredSize(new java.awt.Dimension(1228, 730));
        PanelReceipt.setLayout(new java.awt.GridBagLayout());

        SubPanelSale.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setEnabled(false);
        jScrollPane3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TableReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Mã Hoá Đơn", "Mã Nhân Viên", "Mã Khách hàng"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableReceipt);

        BtnSortReceipt.setText("Lọc Hoá Đơn");
        BtnSortReceipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        LblListReceipts.setText("Danh Sách Hoá Đơn");
        LblListReceipts.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        BtnResetReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh-icon.png"))); // NOI18N
        BtnResetReceipt.setText("Reset tất cả");
        BtnResetReceipt.setActionCommand("");
        BtnResetReceipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnResetReceipt.setName(""); // NOI18N

        BtnInforReceipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnInforReceipt.setText("Thông Tin Hoá Đơn");
        BtnInforReceipt.setActionCommand("");
        BtnInforReceipt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnInforReceiptActionPerformed(evt);
            }
        });

        TfEllipsisReceipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TfEllipsisReceipt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfEllipsisReceipt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TfEllipsisReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubPanelSaleLayout = new javax.swing.GroupLayout(SubPanelSale);
        SubPanelSale.setLayout(SubPanelSaleLayout);
        SubPanelSaleLayout.setHorizontalGroup(
            SubPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanelSaleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblListReceipts)
                .addGap(208, 208, 208))
            .addGroup(SubPanelSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnResetReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnInforReceipt)
                .addGap(81, 81, 81))
            .addGroup(SubPanelSaleLayout.createSequentialGroup()
                .addGroup(SubPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(SubPanelSaleLayout.createSequentialGroup()
                        .addComponent(BtnSortReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TfEllipsisReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        SubPanelSaleLayout.setVerticalGroup(
            SubPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanelSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblListReceipts)
                .addGap(20, 20, 20)
                .addGroup(SubPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEllipsisReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSortReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SubPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnResetReceipt)
                    .addComponent(BtnInforReceipt))
                .addGap(239, 239, 239))
        );

        BtnInforReceipt.getAccessibleContext().setAccessibleName("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        PanelReceipt.add(SubPanelSale, gridBagConstraints);

        SubPanelDetailSale.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setEnabled(false);
        jScrollPane4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TableDetailReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Mã Chi Tiết Hoá Đơn", "Mã Sản Phẩm", "Tên Sản Phẩm", "Sô Lượng"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableDetailReceipt);

        LblDetailReceipt.setText("Các Chi Tiết Hoá Đơn");
        LblDetailReceipt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        LblSubTotalReceipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblSubTotalReceipt.setText("Tổng Cộng");
        LblSubTotalReceipt.setPreferredSize(new java.awt.Dimension(150, 30));

        LblReceiptDiscount.setText("Giảm Giá");
        LblReceiptDiscount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblReceiptDiscount.setPreferredSize(new java.awt.Dimension(150, 30));

        LblReceiptDiscountId.setText("Mã Khuyến Mãi");
        LblReceiptDiscountId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblReceiptDiscountId.setPreferredSize(new java.awt.Dimension(150, 30));

        LblDateReceipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblDateReceipt.setText("Ngày Lập Hoá Đơn");
        LblDateReceipt.setPreferredSize(new java.awt.Dimension(150, 30));

        DPDateReceipt.setEnabled(false);
        DPDateReceipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DPDateReceipt.setPreferredSize(new java.awt.Dimension(300, 30));

        TfSubTotalReceipt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TfSubTotalReceipt.setEnabled(false);
        TfSubTotalReceipt.setPreferredSize(new java.awt.Dimension(300, 30));

        TfReceiptDiscount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TfReceiptDiscount.setEnabled(false);
        TfReceiptDiscount.setPreferredSize(new java.awt.Dimension(300, 30));

        TfReceiptDiscountId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TfReceiptDiscountId.setEnabled(false);
        TfReceiptDiscountId.setPreferredSize(new java.awt.Dimension(300, 30));

        javax.swing.GroupLayout SubPanelDetailSaleLayout = new javax.swing.GroupLayout(SubPanelDetailSale);
        SubPanelDetailSale.setLayout(SubPanelDetailSaleLayout);
        SubPanelDetailSaleLayout.setHorizontalGroup(
            SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanelDetailSaleLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SubPanelDetailSaleLayout.createSequentialGroup()
                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubPanelDetailSaleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SubPanelDetailSaleLayout.createSequentialGroup()
                                .addComponent(LblDateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(DPDateReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SubPanelDetailSaleLayout.createSequentialGroup()
                                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblSubTotalReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblReceiptDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfSubTotalReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfReceiptDiscountId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(SubPanelDetailSaleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LblReceiptDiscountId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(TfReceiptDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubPanelDetailSaleLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(LblDetailReceipt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubPanelDetailSaleLayout.setVerticalGroup(
            SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanelDetailSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblDetailReceipt)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblReceiptDiscountId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfReceiptDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblReceiptDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfReceiptDiscountId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblSubTotalReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSubTotalReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(SubPanelDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DPDateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        LblSubTotalReceipt.getAccessibleContext().setAccessibleName("");
        LblDateReceipt.getAccessibleContext().setAccessibleName("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        PanelReceipt.add(SubPanelDetailSale, gridBagConstraints);

        SaleManagement.addTab("Hoá Đơn", PanelReceipt);

        PanelSale.setBackground(new java.awt.Color(255, 255, 255));
        PanelSale.setPreferredSize(new java.awt.Dimension(1228, 730));

        PanelTitleSale.setBackground(new java.awt.Color(255, 255, 255));

        LblTitleSale.setText("Quản lý Bán Hàng");
        LblTitleSale.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LblTitleSale.setPreferredSize(new java.awt.Dimension(192, 40));

        BtnSaleReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh-icon.png"))); // NOI18N
        BtnSaleReset.setName(""); // NOI18N
        BtnSaleReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnSaleResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTitleSaleLayout = new javax.swing.GroupLayout(PanelTitleSale);
        PanelTitleSale.setLayout(PanelTitleSaleLayout);
        PanelTitleSaleLayout.setHorizontalGroup(
            PanelTitleSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleSaleLayout.createSequentialGroup()
                .addGap(508, 508, 508)
                .addComponent(LblTitleSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnSaleReset)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        PanelTitleSaleLayout.setVerticalGroup(
            PanelTitleSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleSaleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTitleSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSaleReset, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblTitleSale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelDetailProduct.setBackground(new java.awt.Color(255, 255, 255));
        PanelDetailProduct.setPreferredSize(new java.awt.Dimension(420, 328));

        LblProductID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblProductID.setText("Mã sản phẩm");
        LblProductID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblProductID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblProductID.setPreferredSize(new java.awt.Dimension(108, 30));

        TfProductID.setEditable(false);
        TfProductID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TfProductID.setBackground(new java.awt.Color(255, 255, 255));
        TfProductID.setPreferredSize(new java.awt.Dimension(254, 30));
        TfProductID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TfProductIDActionPerformed(evt);
            }
        });

        TfProductName.setEditable(false);
        TfProductName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TfProductName.setBackground(new java.awt.Color(255, 255, 255));
        TfProductName.setPreferredSize(new java.awt.Dimension(254, 30));
        TfProductName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TfProductNameActionPerformed(evt);
            }
        });

        LblProductName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblProductName.setText("Tên sản phẩm");
        LblProductName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblProductName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblProductName.setPreferredSize(new java.awt.Dimension(108, 30));

        LblPriceQuotation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblPriceQuotation.setText("Đơn giả");
        LblPriceQuotation.setBackground(new java.awt.Color(247, 247, 247));
        LblPriceQuotation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblPriceQuotation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblPriceQuotation.setPreferredSize(new java.awt.Dimension(108, 30));

        TfPriceQuotation.setEditable(false);
        TfPriceQuotation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TfPriceQuotation.setBackground(new java.awt.Color(255, 255, 255));
        TfPriceQuotation.setPreferredSize(new java.awt.Dimension(254, 30));
        TfPriceQuotation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TfPriceQuotationActionPerformed(evt);
            }
        });

        LblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblQuantity.setText("Số lượng");
        LblQuantity.setBackground(new java.awt.Color(247, 247, 247));
        LblQuantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblQuantity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblQuantity.setPreferredSize(new java.awt.Dimension(108, 30));

        LblTypeProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTypeProduct.setText("Loại sản phẩm");
        LblTypeProduct.setBackground(new java.awt.Color(247, 247, 247));
        LblTypeProduct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblTypeProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblTypeProduct.setPreferredSize(new java.awt.Dimension(108, 30));

        LblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblEmployee.setText("Nhân viên");
        LblEmployee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblEmployee.setPreferredSize(new java.awt.Dimension(108, 30));

        CbbTypeProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbbTypeProduct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CbbTypeProduct.setPreferredSize(new java.awt.Dimension(254, 30));
        CbbTypeProduct.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CbbTypeProductActionPerformed(evt);
            }
        });

        LblDetailProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDetailProducts.setText("Chi Tiết Sản Phẩm");
        LblDetailProducts.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LblDetailProducts.setForeground(java.awt.Color.blue);

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jSpinner1.setPreferredSize(new java.awt.Dimension(254, 30));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setPreferredSize(new java.awt.Dimension(254, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Khách hàng");
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(108, 30));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(254, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Mã CTKM");
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(108, 30));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(254, 30));

        javax.swing.GroupLayout PanelDetailProductLayout = new javax.swing.GroupLayout(PanelDetailProduct);
        PanelDetailProduct.setLayout(PanelDetailProductLayout);
        PanelDetailProductLayout.setHorizontalGroup(
            PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetailProductLayout.createSequentialGroup()
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetailProductLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(LblDetailProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDetailProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblProductID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblTypeProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPriceQuotation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CbbTypeProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TfPriceQuotation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TfProductID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TfProductName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        PanelDetailProductLayout.setVerticalGroup(
            PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetailProductLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LblDetailProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfProductID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPriceQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPriceQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTypeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbbTypeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDetailProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 286));

        TableDetailProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDetailProduct.setColumnSelectionAllowed(true);
        TableDetailProduct.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(TableDetailProduct);

        FontIcon receiptIcon = FontIcon.of(FontAwesomeSolid.RECEIPT);
        receiptIcon.setIconSize(32);
        receiptIcon.setIconColor(Color.WHITE);
        BtnDeleteSale.setIcon(receiptIcon);
        BtnDeleteSale.setText("Xuất hoá đơn");
        BtnDeleteSale.setBackground(new java.awt.Color(0, 0, 255));
        BtnDeleteSale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnDeleteSale.setForeground(new java.awt.Color(255, 255, 255));
        BtnDeleteSale.setPreferredSize(new java.awt.Dimension(120, 50));
        BtnDeleteSale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnDeleteSaleActionPerformed(evt);
            }
        });

        ProductImage.setPreferredSize(new java.awt.Dimension(156, 156));

        javax.swing.GroupLayout ProductImageLayout = new javax.swing.GroupLayout(ProductImage);
        ProductImage.setLayout(ProductImageLayout);
        ProductImageLayout.setHorizontalGroup(
            ProductImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        ProductImageLayout.setVerticalGroup(
            ProductImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        ImageIcon originalIcon = new ImageIcon("src/main/resources/image/delete-icon,png");
        ImageIcon newIcon = new ImageIcon(originalIcon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
        BtnMakeReceipt.setIcon(newIcon);
        BtnMakeReceipt.setText("Xóa");
        BtnMakeReceipt.setBackground(new java.awt.Color(255, 255, 0));
        BtnMakeReceipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnMakeReceipt.setPreferredSize(new java.awt.Dimension(120, 50));

        FontIcon cartIcon = FontIcon.of(FontAwesomeSolid.SHOPPING_CART);
        cartIcon.setIconSize(32);
        cartIcon.setIconColor(Color.decode("#9D52FF"));
        BtnAddBasket.setText("Thêm vào giỏ hàng");
        BtnAddBasket.setBackground(new java.awt.Color(255, 0, 0));
        BtnAddBasket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAddBasket.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddBasket.setIcon(cartIcon);
        BtnAddBasket.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnAddBasketActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Sản Phẩm");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Giỏ Hàng");
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 143, 12));

        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 302));

        TableBaskets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Đơn giá", "Số lượng", "Thành tiền"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        TableBaskets.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TableBaskets.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(TableBaskets);

        javax.swing.GroupLayout PanelSaleLayout = new javax.swing.GroupLayout(PanelSale);
        PanelSale.setLayout(PanelSaleLayout);
        PanelSaleLayout.setHorizontalGroup(
            PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaleLayout.createSequentialGroup()
                .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSaleLayout.createSequentialGroup()
                        .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelSaleLayout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(jLabel1))
                            .addGroup(PanelSaleLayout.createSequentialGroup()
                                .addGap(362, 362, 362)
                                .addComponent(jLabel2)))
                        .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSaleLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(BtnDeleteSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnMakeReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(PanelSaleLayout.createSequentialGroup()
                                .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelSaleLayout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(BtnAddBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(PanelSaleLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PanelDetailProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(PanelTitleSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelSaleLayout.setVerticalGroup(
            PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaleLayout.createSequentialGroup()
                .addComponent(PanelTitleSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSaleLayout.createSequentialGroup()
                        .addComponent(PanelDetailProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(BtnAddBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(PanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnMakeReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDeleteSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelSaleLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        SaleManagement.addTab("Bán Hàng", PanelSale);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SaleManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaleManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeleteSaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnDeleteSaleActionPerformed
    {//GEN-HEADEREND:event_BtnDeleteSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteSaleActionPerformed

    private void TfPriceQuotationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TfPriceQuotationActionPerformed
    {//GEN-HEADEREND:event_TfPriceQuotationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPriceQuotationActionPerformed

    private void TfProductNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TfProductNameActionPerformed
    {//GEN-HEADEREND:event_TfProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfProductNameActionPerformed

    private void TfProductIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TfProductIDActionPerformed
    {//GEN-HEADEREND:event_TfProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfProductIDActionPerformed

    private void BtnSaleResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnSaleResetActionPerformed
    {//GEN-HEADEREND:event_BtnSaleResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaleResetActionPerformed

    private void BtnAddBasketActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnAddBasketActionPerformed
    {//GEN-HEADEREND:event_BtnAddBasketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddBasketActionPerformed

    private void CbbTypeProductActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CbbTypeProductActionPerformed
    {//GEN-HEADEREND:event_CbbTypeProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbTypeProductActionPerformed

    private void BtnInforReceiptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnInforReceiptActionPerformed
    {//GEN-HEADEREND:event_BtnInforReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInforReceiptActionPerformed

    private void TfEllipsisReceiptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TfEllipsisReceiptActionPerformed
    {//GEN-HEADEREND:event_TfEllipsisReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEllipsisReceiptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddBasket;
    private javax.swing.JButton BtnDeleteSale;
    private javax.swing.JButton BtnInforReceipt;
    private javax.swing.JButton BtnMakeReceipt;
    private javax.swing.JButton BtnResetReceipt;
    private javax.swing.JButton BtnSaleReset;
    private javax.swing.JButton BtnSortReceipt;
    private javax.swing.JComboBox<String> CbbTypeProduct;
    private com.github.lgooddatepicker.components.DatePicker DPDateReceipt;
    private javax.swing.JLabel LblDateReceipt;
    private javax.swing.JLabel LblDetailProducts;
    private javax.swing.JLabel LblDetailReceipt;
    private javax.swing.JLabel LblEmployee;
    private javax.swing.JLabel LblListReceipts;
    private javax.swing.JLabel LblPriceQuotation;
    private javax.swing.JLabel LblProductID;
    private javax.swing.JLabel LblProductName;
    private javax.swing.JLabel LblQuantity;
    private javax.swing.JLabel LblReceiptDiscount;
    private javax.swing.JLabel LblReceiptDiscountId;
    private javax.swing.JLabel LblSubTotalReceipt;
    private javax.swing.JLabel LblTitleSale;
    private javax.swing.JLabel LblTypeProduct;
    private javax.swing.JPanel PanelDetailProduct;
    private javax.swing.JPanel PanelReceipt;
    private javax.swing.JPanel PanelSale;
    private javax.swing.JPanel PanelTitleSale;
    private javax.swing.JPanel ProductImage;
    private javax.swing.JTabbedPane SaleManagement;
    private javax.swing.JPanel SubPanelDetailSale;
    private javax.swing.JPanel SubPanelSale;
    private javax.swing.JTable TableBaskets;
    private javax.swing.JTable TableDetailProduct;
    private javax.swing.JTable TableDetailReceipt;
    private javax.swing.JTable TableReceipt;
    private javax.swing.JTextField TfEllipsisReceipt;
    private javax.swing.JTextField TfPriceQuotation;
    private javax.swing.JTextField TfProductID;
    private javax.swing.JTextField TfProductName;
    private javax.swing.JTextField TfReceiptDiscount;
    private javax.swing.JTextField TfReceiptDiscountId;
    private javax.swing.JTextField TfSubTotalReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
